version: '3'
services:
  app:
    container_name: docker-jest
    restart: always
    build: .
    ports:
      - '6000:3000'
    external_links:
      - mongo
    volumes: 
      - .:/usr/scr/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
    logging: 
      driver: none